project:
  type: book
  output-dir: docs

book:
  title: "Modul Praktikum Visualisasi Data"
  author:
    - name: "[Angga Fathan Rofiqy](https://www.linkedin.com/in/angga-fathan-rofiqy/)"
    - name: "[Nabil Naufal](https://www.linkedin.com/in/nabilnaufal/)"
    - name: "[Sulthan Naufal Sulaeman](https://www.linkedin.com/in/sulthansulii/)"
  date: today
  chapters:
    - index.qmd
    - 01-Bab-1.qmd
    - 02-Bab-2.qmd
    - 03-Bab-3.qmd
    - 04-Bab-4.qmd
    - 05-Bab-5.qmd
    - 06-Bab-6.qmd
    - 07-Bab-7.qmd
    - 08-Bab-8.qmd
  downloads: [pdf, epub]
  site-url: "https://zen-rofiqy.github.io/Modul-VisDat/"
  repo-url: "https://github.com/Zen-Rofiqy/Modul-VisDat"
  repo-actions: [edit, issue]

format:
  html:
    theme:
      light: [cosmo, bootstrap]
      dark: [cosmo, theme-dark.scss]
    toc: true
    number-sections: true
    code-fold: true
    code-overflow: wrap
    code-tools: true
    sidebar: navigation

language:
  label:
    fig: "Gambar "
  ui:
    chapter_name: "Bab "
